In [2]:
import pandas as pd
import numpy as np
from glob import glob
import cv2

In [2]:
image=cv2.imread("mnist/train/1.png")

In [3]:
image

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [4]:
image.shape

(28, 28, 3)

In [5]:
image.flatten()

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [6]:
image.shape

(28, 28, 3)

In [8]:
image=np.array(image)

In [11]:
0.5 in image

False

In [13]:
image.size

2352

In [17]:
for i in range(image.size):
    if image[i] != 1 and image[i] != 0:
        print(image[i])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [18]:
for i in range(image.size):
    print(image[i])

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 1  1  1]
 [ 0  0  0]
 [ 0  0  0]
 [13 13 13]
 [73 73 73]
 [ 0  0  0]
 [ 0  0  0]
 [ 1  1  1]
 

IndexError: index 28 is out of bounds for axis 0 with size 28

In [19]:
print(image[0])

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [20]:
print(image[0].shape)

(28, 3)


In [21]:
print(image[0][0])

[0 0 0]


In [22]:
image2=cv2.imread("vehicle-detection/vehicles/1.png")

In [23]:
image2

array([[[ 42,  36,  34],
        [ 42,  35,  33],
        [ 40,  33,  33],
        ...,
        [123, 110,  92],
        [121, 112, 118],
        [120, 113, 145]],

       [[ 43,  39,  39],
        [ 44,  40,  38],
        [ 44,  39,  37],
        ...,
        [127, 108,  91],
        [128, 126, 118],
        [129, 146, 147]],

       [[ 44,  42,  43],
        [ 48,  44,  42],
        [ 48,  43,  40],
        ...,
        [129, 108,  91],
        [130, 142, 121],
        [132, 178, 152]],

       ...,

       [[224, 246, 254],
        [228, 242, 255],
        [232, 240, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[231, 247, 252],
        [230, 245, 254],
        [229, 243, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[245, 251, 251],
        [238, 250, 253],
        [230, 249, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [24]:
image2.shape

(64, 64, 3)

In [25]:
image2.flatten()

array([ 42,  36,  34, ..., 255, 255, 255], dtype=uint8)

In [3]:
train=pd.read_csv("mnist/train.csv")

In [4]:
train

id  label
0          1      9
1          2      0
2          3      0
3          4      3
4          5      0
...      ...    ...
59995  59996      5
59996  59997      1
59997  59998      3
59998  59999      0
59999  60000      5

[60000 rows x 2 columns]