In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_selection import f_regression

In [2]:
train=pd.read_csv("data3.csv")
train
df=train.drop("diagnosis",axis=1)
df=df.drop("id",axis=1)
print(df.shape)

features=[feat for feat in df]
features=np.array(features)
print(features)
df=df.drop("Unnamed: 32",axis=1)
# print(df['Unnamed: 32'])

#train

(569, 31)
['radius_mean' 'texture_mean' 'perimeter_mean' 'area_mean'
 'smoothness_mean' 'compactness_mean' 'concavity_mean'
 'concave points_mean' 'symmetry_mean' 'fractal_dimension_mean'
 'radius_se' 'texture_se' 'perimeter_se' 'area_se' 'smoothness_se'
 'compactness_se' 'concavity_se' 'concave points_se' 'symmetry_se'
 'fractal_dimension_se' 'radius_worst' 'texture_worst' 'perimeter_worst'
 'area_worst' 'smoothness_worst' 'compactness_worst' 'concavity_worst'
 'concave points_worst' 'symmetry_worst' 'fractal_dimension_worst'
 'Unnamed: 32']


In [3]:
target=train.diagnosis
transformed_target=[]
for t in target:
    if t=="M":
        transformed_target.append(1)
    else:
        transformed_target.append(0)
transformed_target=np.array(transformed_target)

# Forward Feature Selection

In [4]:
ffs = f_regression(df,transformed_target)

In [5]:
variable = [ ]
for i in range(0,len(df.columns)-1):
    if ffs[0][i] >=10:
       variable.append(df.columns[i])

In [6]:
variable=np.array(variable)
variable.shape

(24,)

In [7]:
ffs

(array([6.46981021e+02, 1.18096059e+02, 6.97235272e+02, 5.73060747e+02,
        8.36511234e+01, 3.13233079e+02, 5.33793126e+02, 8.61676020e+02,
        6.95274435e+01, 9.34592949e-02, 2.68840327e+02, 3.90947023e-02,
        2.53897392e+02, 2.43651586e+02, 2.55796780e+00, 5.32473391e+01,
        3.90144816e+01, 1.13262760e+02, 2.41174067e-02, 3.46827476e+00,
        8.60781707e+02, 1.49596905e+02, 8.97944219e+02, 6.61600206e+02,
        1.22472880e+02, 3.04341063e+02, 4.36691939e+02, 9.64385393e+02,
        1.18860232e+02, 6.64439606e+01]),
 array([8.46594057e-096, 4.05863605e-025, 8.43625104e-101, 4.73456431e-088,
        1.05185036e-018, 3.93826311e-056, 9.96655576e-084, 7.10115016e-116,
        5.73338403e-016, 7.59936804e-001, 9.73894866e-050, 8.43332029e-001,
        1.65190518e-047, 5.89552139e-046, 1.10296609e-001, 9.97599465e-013,
        8.26017617e-010, 3.07230877e-024, 8.76641818e-001, 6.30735508e-002,
        8.48229192e-116, 1.07805749e-030, 5.77139714e-119, 2.82884770e-097

In [25]:
variable

array(['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean',
       'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'radius_se',
       'perimeter_se', 'area_se', 'compactness_se', 'concavity_se',
       'concave points_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst'], dtype='<U20')

# Backword feature selection

Given an external estimator that assigns weights to features (e.g., the coefficients of a linear model), the goal of recursive feature elimination (RFE) is to select features by recursively considering smaller and smaller sets of features. First, the estimator is trained on the initial set of features and the importance of each feature is obtained either through any specific attribute (such as coef_, feature_importances_) or callable. Then, the least important features are pruned from current set of features. That procedure is recursively repeated on the pruned set until the desired number of features to select is eventually reached.

RFECV performs RFE in a cross-validation loop to find the optimal number of features.
https://scikit-learn.org/stable/modules/feature_selection.html#rfe

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

lreg = LogisticRegression(penalty = 'l2', C = 0.05, solver = 'liblinear')
rfe = RFE(lreg)
rfe = rfe.fit(df, transformed_target)

In [11]:
rfe.n_features_

15

In [24]:
selected_array=rfe.get_support(True)
selected_array

array([ 0,  1,  2,  5,  6,  7, 11, 13, 20, 21, 22, 25, 26, 27, 28],
      dtype=int64)

In [28]:
selected_features=[]
for s in selected_array:
    selected_features.append(df.columns[s])
selected_features

['radius_mean',
 'texture_mean',
 'perimeter_mean',
 'compactness_mean',
 'concavity_mean',
 'concave points_mean',
 'texture_se',
 'area_se',
 'radius_worst',
 'texture_worst',
 'perimeter_worst',
 'compactness_worst',
 'concavity_worst',
 'concave points_worst',
 'symmetry_worst']