# Data Preprocessing

In [1]:
import pandas as pd
import numpy as np

In [2]:
train=pd.read_csv("dataset/application_data.csv")

In [3]:
train

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0           100002       1         Cash loans           M            N   
1           100003       0         Cash loans           F            N   
2           100004       0    Revolving loans           M            Y   
3           100006       0         Cash loans           F            N   
4           100007       0         Cash loans           M            N   
...            ...     ...                ...         ...          ...   
307506      456251       0         Cash loans           M            N   
307507      456252       0         Cash loans           F            N   
307508      456253       0         Cash loans           F            N   
307509      456254       1         Cash loans           F            N   
307510      456255       0         Cash loans           F            N   

       FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
0                    Y             0          202500.0    406597.5   
1                    N             0          270000.0   1293502.5   
2                    Y             0           67500.0    135000.0   
3                    Y             0          135000.0    312682.5   
4                    Y             0          121500.0    513000.0   
...                ...           ...               ...         ...   
307506               N             0          157500.0    254700.0   
307507               Y             0           72000.0    269550.0   
307508               Y             0          153000.0    677664.0   
307509               Y             0          171000.0    370107.0   
307510               N             0          157500.0    675000.0   

        AMT_ANNUITY  ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20  \
0           24700.5  ...                 0                0                0   
1           35698.5  ...                 0                0                0   
2            6750.0  ...                 0                0                0   
3           29686.5  ...                 0                0                0   
4           21865.5  ...                 0                0                0   
...             ...  ...               ...              ...              ...   
307506      27558.0  ...                 0                0                0   
307507      12001.5  ...                 0                0                0   
307508      29979.0  ...                 0                0                0   
307509      20205.0  ...                 0                0                0   
307510      49117.5  ...                 0                0                0   

       FLAG_DOCUMENT_21 AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                     0                        0.0                       0.0   
1                     0                        0.0                       0.0   
2                     0                        0.0                       0.0   
3                     0                        NaN                       NaN   
4                     0                        0.0                       0.0   
...                 ...                        ...                       ...   
307506                0                        NaN                       NaN   
307507                0                        NaN                       NaN   
307508                0                        1.0                       0.0   
307509                0                        0.0                       0.0   
307510                0                        0.0                       0.0   

        AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                              0.0                        0.0   
1                              0.0                        0.0   
2                              0.0                        0.0   
3                              NaN                        NaN   
4                              

In [4]:
features=[feat for feat in train]
features

['SK_ID_CURR',
 'TARGET',
 'NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_A

In [5]:
train=train.dropna()
train

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
71          100083       0         Cash loans           M            Y   
124         100145       0         Cash loans           F            Y   
152         100179       0         Cash loans           F            Y   
161         100190       0         Cash loans           M            Y   
255         100295       1         Cash loans           M            Y   
...            ...     ...                ...         ...          ...   
307358      456083       0         Cash loans           F            Y   
307359      456084       0         Cash loans           F            Y   
307407      456140       1         Cash loans           F            Y   
307456      456195       0         Cash loans           F            Y   
307482      456226       0         Cash loans           F            Y   

       FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
71                   Y             0          103500.0    573628.5   
124                  Y             1          202500.0    260725.5   
152                  N             0          202500.0    675000.0   
161                  N             0          162000.0    263686.5   
255                  N             1          225000.0   1019205.0   
...                ...           ...               ...         ...   
307358               Y             2          112500.0    361462.5   
307359               Y             1           99000.0    675000.0   
307407               Y             1          261000.0    711454.5   
307456               Y             0           94500.0    270000.0   
307482               Y             0          225000.0    500566.5   

        AMT_ANNUITY  ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20  \
71          24435.0  ...                 0                0                0   
124         16789.5  ...                 0                0                0   
152         53329.5  ...                 0                0                0   
161         24781.5  ...                 0                0                0   
255         31032.0  ...                 1                0                0   
...             ...  ...               ...              ...              ...   
307358      16051.5  ...                 0                0                0   
307359      21906.0  ...                 0                0                0   
307407      47673.0  ...                 0                0                0   
307456      15075.0  ...                 0                0                0   
307482      34969.5  ...                 0                0                0   

       FLAG_DOCUMENT_21 AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
71                    0                        0.0                       0.0   
124                   0                        0.0                       0.0   
152                   0                        0.0                       0.0   
161                   0                        0.0                       0.0   
255                   0                        0.0                       0.0   
...                 ...                        ...                       ...   
307358                0                        0.0                       0.0   
307359                0                        0.0                       0.0   
307407                0                        0.0                       0.0   
307456                0                        0.0                       0.0   
307482                0                        0.0                       0.0   

        AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
71                             0.0                        0.0   
124                            0.0                        0.0   
152                            0.0                        1.0   
161                            0.0                        0.0   
255                            

## Label Encoding

In [6]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()

In [7]:
data_type_list=train.dtypes
type(data_type_list)

pandas.core.series.Series

In [8]:
print("Printing the list of non float columns")
for k,v in train.dtypes.items():
    if v not in ["int32","int64","float64"]:
        print(k,v)

Printing the list of non float columns
NAME_CONTRACT_TYPE object
CODE_GENDER object
FLAG_OWN_CAR object
FLAG_OWN_REALTY object
NAME_TYPE_SUITE object
NAME_INCOME_TYPE object
NAME_EDUCATION_TYPE object
NAME_FAMILY_STATUS object
NAME_HOUSING_TYPE object
OCCUPATION_TYPE object
WEEKDAY_APPR_PROCESS_START object
ORGANIZATION_TYPE object
FONDKAPREMONT_MODE object
HOUSETYPE_MODE object
WALLSMATERIAL_MODE object
EMERGENCYSTATE_MODE object


In [9]:
print("Converting the labels")
for k,v in train.dtypes.items():
    if v not in ["int32","int64","float64"]:
        print("For k "+k)
        print(train[k].unique())
        train[k]=label_encoder.fit_transform(train[k])
        print(train[k].unique())
        

Converting the labels
For k NAME_CONTRACT_TYPE
['Cash loans' 'Revolving loans']


C:\Users\l\AppData\Local\Temp\ipykernel_19132\1205330543.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train[k]=label_encoder.fit_transform(train[k])


[0 1]
For k CODE_GENDER
['M' 'F']
[1 0]
For k FLAG_OWN_CAR
['Y']
[0]
For k FLAG_OWN_REALTY
['Y' 'N']
[1 0]
For k NAME_TYPE_SUITE
['Unaccompanied' 'Family' 'Spouse, partner' 'Children' 'Other_A' 'Other_B'
 'Group of people']
[6 1 5 0 3 4 2]
For k NAME_INCOME_TYPE
['Working' 'Commercial associate' 'State servant']
[2 0 1]
For k NAME_EDUCATION_TYPE
['Secondary / secondary special' 'Higher education' 'Incomplete higher'
 'Lower secondary' 'Academic degree']
[4 1 2 3 0]
For k NAME_FAMILY_STATUS
['Married' 'Separated' 'Single / not married' 'Widow' 'Civil marriage']
[1 2 3 4 0]
For k NAME_HOUSING_TYPE
['House / apartment' 'With parents' 'Municipal apartment'
 'Office apartment' 'Co-op apartment' 'Rented apartment']
[1 5 2 3 0 4]
For k OCCUPATION_TYPE
['Laborers' 'Managers' 'Drivers' 'Core staff' 'Sales staff'
 'High skill tech staff' 'Medicine staff' 'Accountants'
 'Private service staff' 'Cooking staff' 'HR staff' 'Cleaning staff'
 'Security staff' 'Secretaries' 'IT staff' 'Realty agents'
 

In [10]:
print("Checking if any column has string")
for k,v in train.dtypes.items():
    if v not in ["int32","int64","float64"]:
        print(k,v)

Checking if any column has string


## Removing NaN values from data frame

In [11]:
print("Droping target and id column")
df=train.drop("TARGET",axis=1)
df=df.drop("SK_ID_CURR",axis=1)
df

Droping target and id column


NAME_CONTRACT_TYPE  CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  \
71                       0            1             0                1   
124                      0            0             0                1   
152                      0            0             0                0   
161                      0            1             0                0   
255                      0            1             0                0   
...                    ...          ...           ...              ...   
307358                   0            0             0                1   
307359                   0            0             0                1   
307407                   0            0             0                1   
307456                   0            0             0                1   
307482                   0            0             0                1   

        CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
71                 0          103500.0    573628.5      24435.0   
124                1          202500.0    260725.5      16789.5   
152                0          202500.0    675000.0      53329.5   
161                0          162000.0    263686.5      24781.5   
255                1          225000.0   1019205.0      31032.0   
...              ...               ...         ...          ...   
307358             2          112500.0    361462.5      16051.5   
307359             1           99000.0    675000.0      21906.0   
307407             1          261000.0    711454.5      47673.0   
307456             0           94500.0    270000.0      15075.0   
307482             0          225000.0    500566.5      34969.5   

        AMT_GOODS_PRICE  NAME_TYPE_SUITE  ...  FLAG_DOCUMENT_18  \
71             463500.0                6  ...                 0   
124            198000.0                1  ...                 0   
152            675000.0                6  ...                 0   
161            238500.0                6  ...                 0   
255            774000.0                6  ...                 1   
...                 ...              ...  ...               ...   
307358         274500.0                6  ...                 0   
307359         675000.0                1  ...                 0   
307407         643500.0                5  ...                 0   
307456         270000.0                6  ...                 0   
307482         472500.0                6  ...                 0   

        FLAG_DOCUMENT_19  FLAG_DOCUMENT_20  FLAG_DOCUMENT_21  \
71                     0                 0                 0   
124                    0                 0                 0   
152                    0                 0                 0   
161                    0                 0                 0   
255                    0                 0                 0   
...                  ...               ...               ...   
307358                 0                 0                 0   
307359                 0                 0                 0   
307407                 0                 0                 0   
307456                 0                 0                 0   
307482                 0                 0                 0   

        AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
71                             0.0                        0.0   
124                            0.0                        0.0   
152                            0.0                        0.0   
161                            0.0                        0.0   
255                            0.0                        0.0   
...                            ...                        ...   
307358                         0.0                        0.0   
307359                         0.0                        0.0   
307407                         0.0                        0.0   
307456                         0.0                        0.0   
307482                   

In [12]:
target=train.TARGET

# Model with all features

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [14]:
X_train_m1, X_test_m1, y_train_m1, y_test_m1 = train_test_split(df, target, test_size = 0.3)
lgr=LogisticRegression(penalty = 'l2', C = 0.05, solver = 'liblinear')

In [15]:
%%time
lgr.fit(X_train_m1,y_train_m1)

CPU times: total: 297 ms
Wall time: 777 ms


LogisticRegression(C=0.05, solver='liblinear')

In [16]:
lgr.score(X_test_m1,y_test_m1)

0.9380085238279736

# Model with f_regression selected features

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [18]:
f_selected=['NAME_CONTRACT_TYPE', 'AMT_INCOME_TOTAL', 'NAME_EDUCATION_TYPE',
       'DAYS_BIRTH', 'DAYS_EMPLOYED', 'REGION_RATING_CLIENT',
       'REGION_RATING_CLIENT_W_CITY', 'EXT_SOURCE_1', 'EXT_SOURCE_2',
       'EXT_SOURCE_3', 'FLOORSMAX_AVG', 'FLOORSMAX_MODE',
       'FLOORSMAX_MEDI', 'FLAG_DOCUMENT_3']

In [19]:
type(f_selected)

list

In [20]:
f_selected[0]

'NAME_CONTRACT_TYPE'

In [21]:
m2_df=train[f_selected]

In [22]:
m2_df.shape

(8602, 14)

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [24]:
m2_target=train["TARGET"]

In [25]:
X_train_m2, X_test_m2, y_train_m2, y_test_m2 = train_test_split(m2_df, m2_target, test_size = 0.3)
lgr_m2=LogisticRegression(penalty = 'l2', C = 0.05, solver = 'liblinear')

In [26]:
%%time
lgr_m2.fit(X_train_m2,y_train_m2)

CPU times: total: 46.9 ms
Wall time: 43.9 ms


LogisticRegression(C=0.05, solver='liblinear')

In [27]:
lgr_m2.score(X_test_m2,y_test_m2)

0.9387834172801239

# Model with Backword Feature Selection selected features

In [28]:
b_selected=['NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'APARTMENTS_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'FONDKAPREMONT_MODE',
 'TOTALAREA_MODE',
 'WALLSMATERIAL_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DAYS_LAST_PHONE_CHANGE',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_8',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR']

In [29]:
b_selected[0]

'NAME_CONTRACT_TYPE'

In [30]:
m3_df=train[b_selected]
m3_df.shape

(8602, 60)

In [31]:
m3_target=train["TARGET"]

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [33]:
X_train_m3, X_test_m3, y_train_m3, y_test_m3 = train_test_split(m3_df, m3_target, test_size = 0.3)
lgr_m3=LogisticRegression(penalty = 'l2', C = 0.05, solver = 'liblinear')

In [34]:
%%time
lgr_m3.fit(X_train_m3,y_train_m3)

CPU times: total: 172 ms
Wall time: 173 ms


LogisticRegression(C=0.05, solver='liblinear')

In [35]:
lgr_m3.score(X_test_m3,y_test_m3)

0.9434327779930259