In [10]:
import pandas as pd
import numpy as np

In [11]:
train=pd.read_csv("dataset/application_data.csv")

In [12]:
train

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0           100002       1         Cash loans           M            N   
1           100003       0         Cash loans           F            N   
2           100004       0    Revolving loans           M            Y   
3           100006       0         Cash loans           F            N   
4           100007       0         Cash loans           M            N   
...            ...     ...                ...         ...          ...   
307506      456251       0         Cash loans           M            N   
307507      456252       0         Cash loans           F            N   
307508      456253       0         Cash loans           F            N   
307509      456254       1         Cash loans           F            N   
307510      456255       0         Cash loans           F            N   

       FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
0                    Y             0          202500.0    406597.5   
1                    N             0          270000.0   1293502.5   
2                    Y             0           67500.0    135000.0   
3                    Y             0          135000.0    312682.5   
4                    Y             0          121500.0    513000.0   
...                ...           ...               ...         ...   
307506               N             0          157500.0    254700.0   
307507               Y             0           72000.0    269550.0   
307508               Y             0          153000.0    677664.0   
307509               Y             0          171000.0    370107.0   
307510               N             0          157500.0    675000.0   

        AMT_ANNUITY  ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20  \
0           24700.5  ...                 0                0                0   
1           35698.5  ...                 0                0                0   
2            6750.0  ...                 0                0                0   
3           29686.5  ...                 0                0                0   
4           21865.5  ...                 0                0                0   
...             ...  ...               ...              ...              ...   
307506      27558.0  ...                 0                0                0   
307507      12001.5  ...                 0                0                0   
307508      29979.0  ...                 0                0                0   
307509      20205.0  ...                 0                0                0   
307510      49117.5  ...                 0                0                0   

       FLAG_DOCUMENT_21 AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                     0                        0.0                       0.0   
1                     0                        0.0                       0.0   
2                     0                        0.0                       0.0   
3                     0                        NaN                       NaN   
4                     0                        0.0                       0.0   
...                 ...                        ...                       ...   
307506                0                        NaN                       NaN   
307507                0                        NaN                       NaN   
307508                0                        1.0                       0.0   
307509                0                        0.0                       0.0   
307510                0                        0.0                       0.0   

        AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                              0.0                        0.0   
1                              0.0                        0.0   
2                              0.0                        0.0   
3                              NaN                        NaN   
4                              

In [13]:
train=train.dropna()

In [14]:
features=[feat for feat in train]
features

['SK_ID_CURR',
 'TARGET',
 'NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_A

In [15]:
train.dtypes

SK_ID_CURR                      int64
TARGET                          int64
NAME_CONTRACT_TYPE             object
CODE_GENDER                    object
FLAG_OWN_CAR                   object
                               ...   
AMT_REQ_CREDIT_BUREAU_DAY     float64
AMT_REQ_CREDIT_BUREAU_WEEK    float64
AMT_REQ_CREDIT_BUREAU_MON     float64
AMT_REQ_CREDIT_BUREAU_QRT     float64
AMT_REQ_CREDIT_BUREAU_YEAR    float64
Length: 122, dtype: object

In [16]:
list_null=train.isnull().sum()

In [17]:
list_null=list_null.sort_values(ascending=False)
i=0
for l in list_null:
    if l==0:
        break
    i=i+1
i

0

## Label Encoding

In [18]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()

In [13]:
# Sample to convert label 
#train['NAME_CONTRACT_TYPE'].unique()
#label_encoder = preprocessing.LabelEncoder()
#train['NAME_CONTRACT_TYPE']=label_encoder.fit_transform(train['NAME_CONTRACT_TYPE'])
#train['NAME_CONTRACT_TYPE'].unique()

In [19]:
data_type_list=train.dtypes
type(data_type_list)

pandas.core.series.Series

In [20]:
print("Printing the list of non float columns")
for k,v in train.dtypes.items():
    if v not in ["int32","int64","float64"]:
        print(k,v)

Printing the list of non float columns
NAME_CONTRACT_TYPE object
CODE_GENDER object
FLAG_OWN_CAR object
FLAG_OWN_REALTY object
NAME_TYPE_SUITE object
NAME_INCOME_TYPE object
NAME_EDUCATION_TYPE object
NAME_FAMILY_STATUS object
NAME_HOUSING_TYPE object
OCCUPATION_TYPE object
WEEKDAY_APPR_PROCESS_START object
ORGANIZATION_TYPE object
FONDKAPREMONT_MODE object
HOUSETYPE_MODE object
WALLSMATERIAL_MODE object
EMERGENCYSTATE_MODE object


In [21]:
print("Converting the labels")
for k,v in train.dtypes.items():
    if v not in ["int32","int64","float64"]:
        print("For k "+k)
        print(train[k].unique())
        train[k]=label_encoder.fit_transform(train[k])
        print(train[k].unique())
        

Converting the labels
For k NAME_CONTRACT_TYPE
['Cash loans' 'Revolving loans']
[0 1]
For k CODE_GENDER
['M' 'F']
[1 0]
For k FLAG_OWN_CAR
['Y']
[0]
For k FLAG_OWN_REALTY
['Y' 'N']
[1 0]
For k NAME_TYPE_SUITE
['Unaccompanied' 'Family' 'Spouse, partner' 'Children' 'Other_A' 'Other_B'
 'Group of people']
[6 1 5 0 3 4 2]
For k NAME_INCOME_TYPE
['Working' 'Commercial associate' 'State servant']
[2 0 1]
For k NAME_EDUCATION_TYPE
['Secondary / secondary special' 'Higher education' 'Incomplete higher'
 'Lower secondary' 'Academic degree']
[4 1 2 3 0]
For k NAME_FAMILY_STATUS
['Married' 'Separated' 'Single / not married' 'Widow' 'Civil marriage']
[1 2 3 4 0]
For k NAME_HOUSING_TYPE
['House / apartment' 'With parents' 'Municipal apartment'
 'Office apartment' 'Co-op apartment' 'Rented apartment']
[1 5 2 3 0 4]
For k OCCUPATION_TYPE
['Laborers' 'Managers' 'Drivers' 'Core staff' 'Sales staff'
 'High skill tech staff' 'Medicine staff' 'Accountants'
 'Private service staff' 'Cooking staff' 'HR staf

C:\Users\l\AppData\Local\Temp\ipykernel_14884\1205330543.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train[k]=label_encoder.fit_transform(train[k])


In [22]:
print("Checking is any null value is there")
for k in train:
    if train[k].isnull().any():
        print(k)

Checking is any null value is there


In [23]:
print("Checking if any column has string")
for k,v in train.dtypes.items():
    if v not in ["int32","int64","float64"]:
        print(k,v)

Checking if any column has string


In [27]:
print("Droping target and id column")
df=train.drop("TARGET",axis=1)
df=df.drop("SK_ID_CURR",axis=1)
df

Droping target and id column


NAME_CONTRACT_TYPE  CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  \
71                       0            1             0                1   
124                      0            0             0                1   
152                      0            0             0                0   
161                      0            1             0                0   
255                      0            1             0                0   
...                    ...          ...           ...              ...   
307358                   0            0             0                1   
307359                   0            0             0                1   
307407                   0            0             0                1   
307456                   0            0             0                1   
307482                   0            0             0                1   

        CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
71                 0          103500.0    573628.5      24435.0   
124                1          202500.0    260725.5      16789.5   
152                0          202500.0    675000.0      53329.5   
161                0          162000.0    263686.5      24781.5   
255                1          225000.0   1019205.0      31032.0   
...              ...               ...         ...          ...   
307358             2          112500.0    361462.5      16051.5   
307359             1           99000.0    675000.0      21906.0   
307407             1          261000.0    711454.5      47673.0   
307456             0           94500.0    270000.0      15075.0   
307482             0          225000.0    500566.5      34969.5   

        AMT_GOODS_PRICE  NAME_TYPE_SUITE  ...  FLAG_DOCUMENT_18  \
71             463500.0                6  ...                 0   
124            198000.0                1  ...                 0   
152            675000.0                6  ...                 0   
161            238500.0                6  ...                 0   
255            774000.0                6  ...                 1   
...                 ...              ...  ...               ...   
307358         274500.0                6  ...                 0   
307359         675000.0                1  ...                 0   
307407         643500.0                5  ...                 0   
307456         270000.0                6  ...                 0   
307482         472500.0                6  ...                 0   

        FLAG_DOCUMENT_19  FLAG_DOCUMENT_20  FLAG_DOCUMENT_21  \
71                     0                 0                 0   
124                    0                 0                 0   
152                    0                 0                 0   
161                    0                 0                 0   
255                    0                 0                 0   
...                  ...               ...               ...   
307358                 0                 0                 0   
307359                 0                 0                 0   
307407                 0                 0                 0   
307456                 0                 0                 0   
307482                 0                 0                 0   

        AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
71                             0.0                        0.0   
124                            0.0                        0.0   
152                            0.0                        0.0   
161                            0.0                        0.0   
255                            0.0                        0.0   
...                            ...                        ...   
307358                         0.0                        0.0   
307359                         0.0                        0.0   
307407                         0.0                        0.0   
307456                         0.0                        0.0   
307482                   

In [24]:
target=train.TARGET

## Forward Regression

Univariate linear regression tests* returning F-statistic and p-values.

*test the linearity of the relationship between the response variable and different predictor variables.

A F-test (Wikipedia) is a way of comparing the significance of the improvement of a model, with respect to the addition of new variables. You can use it when have a basic model M0 and a more complicated model M1, which contains all variables from M0 and some more. The F-test tells you if M1 is significantly better than M0, with respect to a p-value.

In [25]:
from sklearn.feature_selection import f_regression

In [28]:
ffs = f_regression(df,target)

c:\users\l\appdata\local\programs\python\python38\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:289: RuntimeWarning: divide by zero encountered in true_divide
  correlation_coefficient /= X_norms
c:\users\l\appdata\local\programs\python\python38\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:289: RuntimeWarning: invalid value encountered in true_divide
  correlation_coefficient /= X_norms
c:\users\l\appdata\local\programs\python\python38\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:358: RuntimeWarning: invalid value encountered in true_divide
  f_statistic = corr_coef_squared / (1 - corr_coef_squared) * deg_of_freedom


In [29]:
forward_selected_variable = [ ]
for i in range(0,len(df.columns)-1):
    if ffs[0][i] >=10:
       forward_selected_variable.append(df.columns[i])

In [30]:
forward_selected_variable=np.array(forward_selected_variable)
forward_selected_variable.shape

(14,)

In [31]:
forward_selected_variable

array(['NAME_CONTRACT_TYPE', 'AMT_INCOME_TOTAL', 'NAME_EDUCATION_TYPE',
       'DAYS_BIRTH', 'DAYS_EMPLOYED', 'REGION_RATING_CLIENT',
       'REGION_RATING_CLIENT_W_CITY', 'EXT_SOURCE_1', 'EXT_SOURCE_2',
       'EXT_SOURCE_3', 'FLOORSMAX_AVG', 'FLOORSMAX_MODE',
       'FLOORSMAX_MEDI', 'FLAG_DOCUMENT_3'], dtype='<U27')

## Backword Feature Selection

Given an external estimator that assigns weights to features (e.g., the coefficients of a linear model), the goal of recursive feature elimination (RFE) is to select features by recursively considering smaller and smaller sets of features. First, the estimator is trained on the initial set of features and the importance of each feature is obtained either through any specific attribute (such as coef_, feature_importances_) or callable. Then, the least important features are pruned from current set of features. That procedure is recursively repeated on the pruned set until the desired number of features to select is eventually reached.

RFECV performs RFE in a cross-validation loop to find the optimal number of features. https://scikit-learn.org/stable/modules/feature_selection.html#rfe

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

lreg = LogisticRegression(penalty = 'l2', C = 0.05, solver = 'liblinear')
rfe = RFE(lreg)
rfe = rfe.fit(df, target)

In [33]:
rfe.n_features_

60

In [34]:
selected_array=rfe.get_support(True)
selected_array

array([  0,   1,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        15,  16,  17,  18,  19,  20,  21,  23,  24,  26,  27,  28,  29,
        30,  31,  37,  38,  39,  40,  41,  42,  44,  45,  49,  50,  56,
        58,  59,  63,  64,  67,  70,  72,  73,  77,  78,  84,  86,  87,
        89,  90,  91,  93,  95, 100, 118, 119], dtype=int64)

In [35]:
selected_features=[]
for s in selected_array:
    selected_features.append(df.columns[s])
selected_features

['NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'APARTMENTS_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'FLOORSMAX